# Generated by Django 6.0.3 on 2026-03-27 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverificationtoken',
            old_name='uid',
            new_name='user',
        ),
    ]
