# Generated by Django 6.0.3 on 2026-03-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_rename_uid_emailverificationtoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
