# Generated by Django 6.0.3 on 2026-03-27 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_emailverificationtoken_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='is_verified',
        ),
    ]
