# Generated by Django 6.0.3 on 2026-03-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_remove_emailverificationtoken_is_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
