# Generated by Django 6.0.3 on 2026-03-13 12:30

import account.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=account.models.fields.PhoneNumberField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
