# Generated by Django 6.0.3 on 2026-03-14 11:54

import account.validators.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[account.validators.user.validate_address]),
        ),
    ]
