# Generated by Django 6.0.3 on 2026-03-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mid_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nick_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
