# Generated by Django 6.0.3 on 2026-03-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mid_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
