# Generated by Django 6.0.3 on 2026-03-28 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_emailverificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='is_used',
        ),
    ]
