# Generated by Django 6.0.3 on 2026-03-28 09:30

import account.models.verify_email
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_emailverificationtoken_is_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=account.models.verify_email._generate_secret, max_length=128)),
                ('expired_at', models.DateTimeField(default=account.models.verify_email._generate_exp_time)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_verify_tokens',
            },
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
