# Generated by Django 6.0.3 on 2026-04-02 17:04

import account.models.verify_email
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_emailverifyotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='emailverifyotp',
            name='otp',
            field=models.CharField(default=account.models.verify_email.generate_otp, max_length=6),
        ),
    ]
