# Generated by Django 6.0.3 on 2026-04-09 03:44

import account.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_user_avatar_alter_emailverifyotp_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.user.upload_avatar),
        ),
    ]
