# Generated by Django 6.0.3 on 2026-04-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyotp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
