# Generated by Django 6.0.3 on 2026-04-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_emailverifyotp_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverifyotp',
            name='attempts',
        ),
    ]
